/*
	This program implements gradient descent for  linear in C
*/

#include "linear-regression.h"


int main(void) {

	srand(time(NULL));  // Seed the random number generator

	// --------------------------------STEP 1--------------------------------<Get Target Linear Function>
	// define from user input the target linear function that 
	// our randomly initialize model will be trained to approximation
	double w_true = 0, b_true = 0;

	get_target_function(&w_true, &b_true);


	// --------------------------------STEP 2--------------------------------<Get Training Datasets from the inputted Function>
	// This creates an array of 100 xy_coord structs
	// called train. It will be populated with examples 
	// from the target linear model for use as the training
	// and test datasets respectively
	xy_coord train[100];


	// These variables will be used to house the X and y coordinates generated by
	// The linear function in order to populate our trian and test arrays with them

	int X = 0;   
	double y = 0;
	
	printf("\n\nNow Populating the Train Set with Examples From f(x)...\n\n");

	// populate train set

	for (int i = 1; i <= 100; i++) {
		// get random x value
		X = random_x();

		// get linear target y value from the x val
		y = linear_function(X, w_true, b_true);

		// populate array with x and y vals
		train[i - 1].x = X;
		train[i - 1].y = y;
	}
	
	// --------------------------------STEP 3--------------------------------<Intialize the Hypothesis Function Weights>

	// initialize model parameters to use as our model
	double w_theta = 1,
		b_theta = 1;

	// --------------------------------STEP 3--------------------------------<Train Model>

	// Initialize array to house the training predictions
	double train_pred[100] = { 0 };

	// initialize array to hold targets 
	double train_targets[100] = { 0 };

	// intialize gradient struct for learning update
	gradient grad;
	grad.w_update = 0;
	grad.b_update = 0;

	// intializer num epochs and learning rate
	int epochs = 100;
	double learning_rate = 0.0001;

	// training loop
	for (int i = 1; i <= epochs; i++) {
		grad = epoch(w_theta, b_theta, train_pred, train, train_targets, grad);
		printf("\n\nEpoch %d ---- Gradient When Returned To Main: dJ/dw = %lf ---- dJ/db = %lf", i, grad.w_update, grad.b_update);

		// learning rule
		w_theta = w_theta - (learning_rate * grad.w_update);
		b_theta = b_theta - (learning_rate + grad.b_update);

	}

	// display final model
	printf("\n\n-----------RESULTS!!!-----------");
	printf("\n\n\nTarget Model: y = %lfx + %lf", w_true, b_true);
	printf("\n\nHypothesis: y = %lfx + %lf", w_theta, b_theta);
	printf("\n\n-----------RESULTS!!!-----------\n\n");

	return 0;
}
